#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 2

#define ENCODERS_PAD_A { F4, D2 }
#define ENCODERS_PAD_B { F5, D4 }
#define ENCODER_RESOLUTIONS { 2, 2 }
#define ENCODER_MAP_KEY_DELAY 10


#define WS2812_DI_PIN B6
#define RGB_MATRIX_LED_COUNT 12