LTO_ENABLE = yes

KEY_OVERRIDE_ENABLE = no
TAP_DANCE_ENABLE = no
QMK_SETTINGS = no
MUSIC_ENABLE = no
COMBO_ENABLE = no

ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = no

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
WS2812_DRIVER = bitbang
WS2812_DRIVER_REQUIRED = yes